### PR TITLE
Fix bug with SignChecker when NaNs are present

### LINKED ISSUE #254: Bug with SignChecker
The implementation of sign checker is to do the following computation

```julia
nanmean(var.data .> 0)
```

This doesn't work, because `NaN .> 0` is `false` and not `NaN`.

### PR DESCRIPTION
**Pull request by ph-kev**
The original code is `nanmean(var.data .> 0)`. This does not work, because `NaN > 0` is `false` and not `NaN`.

closes #254

### CODE REVIEW

File: ext/checkers.jl [hunk 1]
```diff
@@ -264,7 +264,14 @@ function Checker.check(
...
     # should not change that much with additional times.
-    sim_pos_proportion = nanmean(var.data .> 0)
+    positive_count = 0
+    count = 0
+    for val in var.data
+        isnan(val) && continue
+        count += 1
+        positive_count += val > 0
+    end
+    sim_pos_proportion = positive_count / count
```
Comment (nefrathenrici) [inline ext/checkers.jl]: I think this could be simpler:
```suggestion
    valid = @. !isnan(var.data)
    sim_pos_proportion = sum((var.data .> 0) .& valid) / sum(valid)
```
