### PR TITLE
Fix failure_rate kwarg in WorkerBackend, improve error message

### LINKED ISSUE #164: error when exceeding model failure rate should inform user that this is why it fails
[Here](https://github.com/CliMA/ClimaCalibrate.jl/blob/e040d672e80faacb916bb9cb520d77f6481b7be8/src/workers.jl#L43) the worker's code throws an error if the failure rate exceeds some default threshold rate but doesn't indicate that the failure rate is the source of the error. The message should be improved to indicate this. 

For example we have:
```out
ERROR: LoadError: Ensemble for iter 0 had a 56.00000000000001% failure rate
```
It would be more informative to have a message like 
```bash
ERROR: ErrorException: Halting execution because iter 0 had a 56% failure rate which is higher than the DEFAULT_FAILURE_RATE.
```
The docstring for the calibrate function should also be updated to note this, e.g. [here](https://github.com/CliMA/ClimaCalibrate.jl/blob/e040d672e80faacb916bb9cb520d77f6481b7be8/src/backends.jl#L233)

### PR DESCRIPTION
**Pull request by nefrathenrici**
## Purpose 

Closes #164 

## Content

Fixes the failure_rate kwarg when using the WorkerBackend and improved the error message to be more informative

----
- [ ] I have read and checked the items on the review checklist.

### CODE REVIEW

File: src/workers.jl [hunk 1]
```diff
@@ -39,8 +39,10 @@ function run_worker_iteration(
     end
     iter_failure_rate = nfailures / ensemble_size
     if iter_failure_rate > failure_rate
-        error(
-            "Ensemble for iter $iter had a $(iter_failure_rate * 100)% failure rate",
+        throw(
+            ErrorException(
+                "Execution halted: Iteration 0 had a $(round(iter_failure_rate * 100; digits=2))% failure rate, exceeding the maximum allowed threshold of $(failure_rate * 100)%.",
```
Comment (ph-kev) [inline src/workers.jl:44]:
```suggestion
        error(
                "Execution halted: Iteration $iter had a $(round(iter_failure_rate * 100; digits=2))% failure rate, exceeding the maximum allowed threshold of $(failure_rate * 100)%.",
```

**Review by ph-kev — CHANGES_REQUESTED** [review]

File: src/workers.jl (hunk 1 above)
Comment (nefrathenrici) [reply src/workers.jl:44]: Ah, that is a sloppy typo. Thanks for catching it!

**Review by ph-kev — APPROVED** [review]

**Review by Julians42 — APPROVED** [review]
Looks good - thanks Nat!
