### PR TITLE
Fix `DerechoBackend`

### LINKED ISSUE #207: `DerechoBackend` is broken
PBS broke when I added the `exeflags` keyword argument to the slurm job scheduler and didn't add proper support for PBS.

This should be fixed and unit-tested to catch future breaking interface changes.

[Sample build](https://buildkite.com/clima/climacalibrate-derecho/builds/344#0197f6db-42d0-463b-bec8-4a054c0cb00c)

### PR DESCRIPTION
**Pull request by nefrathenrici**
## Purpose 

Fixes `DerechoBackend`. Closes #207 

## Content

Properly passes `exeflags` kwarg through to `pbs_model_run` to match the slurm implementation

----
- [ ] I have read and checked the items on the review checklist.

### CODE REVIEW

File: test/pbs_unit_tests.jl [hunk 1]
```diff
@@ -86,31 +86,31 @@ test_cmd = """
...
+
+# # Test batch cancellation
+# jobids = ntuple(x -> submit_cmd_helper(test_cmd), 5)
+
+# CAL.kill_job.(jobids)
+# sleep(10)
+# for jobid in jobids
+#     @test CAL.job_completed(jobid)
+#     @test CAL.job_failed(jobid)
+# end
```
Comment (ph-kev) [inline test/pbs_unit_tests.jl:116]: I think you accidentally commented out this part of the test, unless you want to delete it?

**Review by ph-kev — APPROVED** [review]

File: test/pbs_unit_tests.jl (hunk 1 above)
Comment (nefrathenrici) [reply test/pbs_unit_tests.jl:116]: Thanks for catching that! It looks like the tests are still breaking with a different error.
